name: Greeting
on: [push,workflow_dispatch]
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: echo "Hello, World!"
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: |
                echo "Cloning repo..."
                echo "${{toJson(github)}}"
                git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


